### ISSUE TITLE
port configuration of -1 can allocate illegal ports 

### ISSUE THREAD

**Issue by cydergoth** [ruslanys/sample-spring-boot-netty#1]
https://github.com/ruslanys/sample-spring-boot-netty/blob/9cc9ab629e2b8eb45d86cc2226f76511ca3eca95/src/main/kotlin/me/ruslanys/web/HttpServer.kt#L29

When the port is set to -1, a random port is allocated. Most operating system restrict non-privileged processes to ports above 1024. In addition, the available port range may be further restricted by the kernel configuration. This method does not account for those restrictions and may generate an illegal port, especially if local tests are running without root privileges.

**Comment by ruslanys** [comment]
Ah, yes! You are right.
I've set the lower limit and excluded IANA range.

Thank you! Appreciate your help! 🙏

**Comment by ruslanys** [comment]
Take a look at #2
